# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GiftRenderDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # pod 'GiftRendererKit', :podspec => '../GiftRenderKit/GiftRendererKit.podspec'
  pod 'GiftRendererKit',  '~> 1.0.0'

end
